#!/bin/bash

set -eo pipefail

echo "nncpnet: Configuring system."

NNCPCFGDIR="/tmp/nncpnet/cfg"

if [ -n "$NNCPNET_MYNODENAME" ]; then
    echo "$NNCPNET_MYNODENAME" > /tmp/nncpnet/cfg/mynodename
fi

if [ -n "$NNCPNET_ID" ]; then
    echo "$NNCPNET_ID" > /tmp/nncpnet/cfg/selfpub/id
fi

if [ -n "$NNCPNET_EXCHPUB" ]; then
    echo "$NNCPNET_EXCHPUB" > /tmp/nncpnet/cfg/selfpub/exchpub
fi

if [ -n "$NNCPNET_NOISEPUB" ]; then
    echo "$NNCPNET_NOISEPUB" > /tmp/nncpnet/cfg/selfpub/noisepub
fi

if [ -n "$NNCPNET_SIGNPUB" ]; then
    echo "$NNCPNET_SIGNPUB" > /tmp/nncpnet/cfg/selfpub/signpub
fi

if [ -n "$NNCPNET_EXCHPRV" ]; then
    echo "$NNCPNET_EXCHPRV" > /tmp/nncpnet/cfg/selfprv/exchprv
fi

if [ -n "$NNCPNET_NOISEPRV" ]; then
    echo "$NNCPNET_NOISEPRV" > /tmp/nncpnet/cfg/selfprv/noiseprv
fi

if [ -n "$NNCPNET_SIGNPRV" ]; then
    echo "$NNCPNET_SIGNPRV" > /tmp/nncpnet/cfg/selfprv/signprv
fi

if [ -n "$NNCPNET_LOCALUSER_NAME" ]; then
    echo "$NNCPNET_LOCALUSER_NAME" > /tmp/nncpnet/localuser-name
fi

if [ -n "$NNCPNET_LOCALUSER_UID" ]; then
    echo "$NNCPNET_LOCALUSER_UID" > /tmp/nncpnet/localuser-uid
fi

if [ -n "$NNCPNET_LOCALUSER_COMMENT" ]; then
    echo "$NNCPNET_LOCALUSER_COMMENT" > /tmp/nncpnet/localuser-comment
fi

if [ -n "$NNCPNET_LOCALUSER_PWCRYPT" ]; then
	echo "$NNCPNET_LOCALUSER_PWCRYPT" > /tmp/nncpnet/localuser-pwcrypt
	chmod 0600 /tmp/nncpnet/localuser-pwcrypt
fi

if [ -n "$NNCPNET_BRIDGE_MODE" ]; then
	echo "$NNCPNET_BRIDGE_MODE" > /tmp/nncpnet/bridge_mode
fi

if [ -n "$NNCPNET_BRIDGE_HOST" ]; then
	echo "$NNCPNET_BRIDGE_HOST" > /tmp/nncpnet/bridge_host
fi

# Setting this will cause no nodelist to be requested or processed.
if [ -n "$NNCPNET_NO_NODELIST" ]; then
    echo "1" > /tmp/nncpnet/no-nodelist
fi

# Set to a comma-separated list of nodes to relay through in order to reach
# quux.
if [ -n "$NNCPNET_QUUX_VIA" ]; then
    echo "$NNCPNET_QUUX_VIA" | sed 's/,/\n/g' > /tmp/nncpnet/nncp-cfg-tmpl/neigh/quux/via
fi

EXITCODE=0

for FILE in /tmp/nncpnet/cfg/mynodename /tmp/nncpnet/cfg/selfpub/{id,exchpub,noisepub,signpub} \
    /tmp/nncpnet/cfg/selfprv/{exchprv,noiseprv,signprv}; do
    if [ ! -f "$FILE" ]; then
        echo " *** ERROR: Missing file $FILE or related environment variable"
        echo " *** Expect system to be broken"
        EXITCODE=6
    fi
done

if [ "$EXITCODE" = 0 ]; then
    cp /tmp/nncpnet/cfg/selfpub/* /tmp/nncpnet/nncp-cfg-tmpl/self
    cp /tmp/nncpnet/cfg/selfprv/* /tmp/nncpnet/nncp-cfg-tmpl/self
    echo "nncpnet: All required configuration is present."
fi

exit "$EXITCODE"
